apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ticketportal/catalog
    newTag: local
  - name: ticketportal/booking
    newTag: local
  - name: ticketportal/order
    newTag: local
  - name: ticketportal/payment
    newTag: local
  - name: ticketportal/gateway
    newTag: local
